curations:
  packages:
  - id: "PyPI::werkzeug:3.0.0"
    curations:
      comment: "Declaring license [https://github.com/pallets/werkzeug/blob/3.0.0/LICENSE.rst]"
      concluded_license: "BSD-3-Clause"
  - id: "PyPI::tiktoken:0.4.0"
    curations:
      comment: "Declaring license [https://github.com/openai/tiktoken/blob/0.4.0/LICENSE]"
      concluded_license: "MIT"