---
excludes:
  scopes:
  - pattern: "dev"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."
  - pattern: "lint"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for static code analysis only."
  - pattern: "test"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for testing only."
license_choices:
  repository_license_choices:
  - given: FTL OR GPL-2.0-or-later
    choice: FTL
resolutions:
  rule_violations:
    - message: ".*PyPI::aiocache:0\\.12\\.2.*"
      reason: 'CANT_FIX_EXCEPTION'
      comment: 'BSD 3-Clause "New" or "Revised" License: https://github.com/aio-libs/aiocache/blob/v0.12.2/LICENSE'
    - message: ".*PyPI::httpcore:1\\.0\\.2.*"
      reason: 'CANT_FIX_EXCEPTION'
      comment: 'BSD 3-Clause "New" or "Revised" License: https://github.com/encode/httpcore/blob/1.0.2/LICENSE.md'
    - message: ".*PyPI::httpx:0\\.25\\.2.*"
      reason: 'CANT_FIX_EXCEPTION'
      comment: 'BSD 3-Clause "New" or "Revised" License: https://github.com/encode/httpx/blob/0.25.2/LICENSE.md'
    - message: ".*PyPI::pypdf:4\\.2\\.0.*"
      reason: 'CANT_FIX_EXCEPTION'
      comment: 'BSD-3-Clause License: https://github.com/py-pdf/pypdf/issues/496'
    - message: ".*PyPI::numpy:2\\.0\\.0.*"
      reason: 'CANT_FIX_EXCEPTION'
      comment: 'BSD License: https://github.com/numpy/numpy/blob/v2.0.0/LICENSE.txt'