from aidial_adapter_vertexai.utils.env import get_env_int

DEFAULT_REGION_ENV_VAR = "DEFAULT_REGION"
DEFAULT_PROJECT_ENV_VAR = "GCP_PROJECT_ID"

ANTHROPIC_MAX_RETRY_ATTEMPTS = get_env_int("ANTHROPIC_MAX_RETRY_ATTEMPTS", 0)
GOOGLE_GENAI_MAX_RETRY_ATTEMPTS = get_env_int(
    "GOOGLE_GENAI_MAX_RETRY_ATTEMPTS", 0
)

HTTP_MAX_CONNECTIONS = get_env_int("HTTP_MAX_CONNECTIONS", 250)
HTTP_MAX_KEEPALIVE_CONNECTIONS = get_env_int(
    "HTTP_MAX_KEEPALIVE_CONNECTIONS", 75
)
HTTP_POOL_TIMEOUT = get_env_int("HTTP_POOL_TIMEOUT", 10)

HTTP_CONNECT_TIMEOUT = 5.0
HTTP_READ_TIMEOUT = 10 * 60
HTTP_WRITE_TIMEOUT = 10 * 60
