from typing import assert_never

import vertexai.preview.generative_models as generative_models
from aidial_sdk.chat_completion import FinishReason

from aidial_adapter_vertexai.chat.gemini.error import FinishReasonOtherError

GenFinishReason = generative_models.FinishReason


def to_openai_finish_reason(
    finish_reason: GenFinishReason, retriable: bool
) -> FinishReason | None:
    match finish_reason:
        case GenFinishReason.FINISH_REASON_UNSPECIFIED:
            return None
        case GenFinishReason.MAX_TOKENS:
            return FinishReason.LENGTH
        case GenFinishReason.STOP:
            return FinishReason.STOP
        case (
            GenFinishReason.SAFETY
            | GenFinishReason.RECITATION
            | GenFinishReason.BLOCKLIST
            | GenFinishReason.PROHIBITED_CONTENT
            | GenFinishReason.SPII
        ):
            return FinishReason.CONTENT_FILTER

        # The following finish reasons could be usually fixed with a retry
        case GenFinishReason.OTHER:
            raise FinishReasonOtherError(
                msg="The model terminated generation unexpectedly",
                retriable=retriable,
            )
        case GenFinishReason.MALFORMED_FUNCTION_CALL:
            raise FinishReasonOtherError(
                msg="The function call generated by the model is invalid",
                retriable=retriable,
            )
        case _:
            assert_never(finish_reason)
