from typing import assert_never

from aidial_sdk.chat_completion import FinishReason
from google.genai.types import FinishReason as GenAIFinishReason

from aidial_adapter_vertexai.chat.gemini.error import FinishReasonOtherError

_EARLY_TERMINATION_ERROR = "The model terminated generation unexpectedly"
_INVALID_FUNCTION_CALL_ERROR = (
    "The function call generated by the model is invalid"
)


def genai_to_openai_finish_reason(
    finish_reason: GenAIFinishReason | None,
    finish_message: str | None,
    retriable: bool,
) -> FinishReason | None:
    if not finish_reason:
        return None

    def _add_finish_message(msg: str):
        if finish_message:
            return f"{msg}: {finish_message}"
        else:
            return msg

    match finish_reason:
        case GenAIFinishReason.FINISH_REASON_UNSPECIFIED:
            return None
        case GenAIFinishReason.MAX_TOKENS:
            return FinishReason.LENGTH
        case GenAIFinishReason.STOP:
            return FinishReason.STOP
        case (
            GenAIFinishReason.SAFETY
            | GenAIFinishReason.RECITATION
            | GenAIFinishReason.BLOCKLIST
            | GenAIFinishReason.PROHIBITED_CONTENT
            | GenAIFinishReason.SPII
            | GenAIFinishReason.IMAGE_SAFETY
            | GenAIFinishReason.LANGUAGE  # NOTE: undocumented
        ):
            return FinishReason.CONTENT_FILTER
        case GenAIFinishReason.OTHER:
            raise FinishReasonOtherError(
                msg=_add_finish_message(_EARLY_TERMINATION_ERROR),
                retriable=retriable,
            )
        case (
            GenAIFinishReason.MALFORMED_FUNCTION_CALL
            | GenAIFinishReason.UNEXPECTED_TOOL_CALL
        ):
            raise FinishReasonOtherError(
                msg=_add_finish_message(_INVALID_FUNCTION_CALL_ERROR),
                retriable=retriable,
            )
        case _:
            assert_never(finish_reason)
